[package]
name = "day16"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
regex = "1.10.4"
once_cell = "1.19.0"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
