[package]
name = "day17"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
anyhow = "1.0.86"
int-enum = "1.1.2"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
