[package]
name = "day10"
version = "0.1.0"
authors = ["leizy <leizy_post@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
regex = "1"
image = "0.24.3"
